### ISSUE TITLE
Not working anymore with Qt 5.11

### ISSUE THREAD

**Issue by ghost** [Moussa-Ball/BorderlessWindowQt-Modern-Gui#3]
Hi, 

So with Qt 5.10.1, the app works perfectly. But if I compile with 5.11.1 it looks like this :

<img width="1680" alt="screen shot 2018-07-09 at 22 38 54" src="https://user-images.githubusercontent.com/33607237/42474777-e2e42f28-83c8-11e8-945e-e5ee290328ff.png">

**Comment by Moussa-Ball** [comment]
I advise you to use visual studio with qt as well as the latest version of windows 10 sdk. In the project, I used the windows 7 sdk and I fear that it is because of the old.

**Comment by Moussa-Ball** [comment]
I used C: \ Program Files \ Microsoft SDKs \ Windows \ v7.1 \ "while the windows 10 is more recent, with visual studio 2015 it works fine on my computer.

**Comment by ghost** [comment]
I tried with Visual Studio 2017 and Windows 10 sdk, same result. Do you use Windows 10 or 7 ?

**Comment by Moussa-Ball** [comment]
Windows 10

**Comment by Moussa-Ball** [comment]
I'm going to put on line tonight a project that I started and that uses borderless window with visual studio.

**Comment by ghost** [comment]
Ok, I will try to install windows 7 sdk

**Comment by Moussa-Ball** [comment]
No, but Windows 10 SDK. Do you have Visual Studio 2015 or higher.

**Comment by ghost** [comment]
With the Windows 10 SDK and Visual Studio 2017, I still have the same weird rendering

**Comment by Moussa-Ball** [comment]
Now wait for me to commit tonight.

**Comment by ghost** [comment]
Alright

**Comment by Moussa-Ball** [comment]
I'm going to commit with a real visual studio project with Qt.

**Comment by Moussa-Ball** [comment]
Download the project, opens DesignerStudio.sln and compile it with visual studio.

**Comment by ghost** [comment]
I got those errors :
<img width="1275" alt="screen shot 2018-07-11 at 18 19 37" src="https://user-images.githubusercontent.com/33607237/42585888-18bde796-8537-11e8-94f3-c04a2d7a7c5d.png">

**Comment by Moussa-Ball** [comment]
You're french

**Comment by Moussa-Ball** [comment]
Otherwise I could help you directly with a live video.

**Comment by Moussa-Ball** [comment]
You have to reference the Studio.Softer project on visual studio and indicate the path of the folder containing the headers folder.

**Comment by ghost** [comment]
I will try thank you. Just how did you know I'm French?

**Comment by Moussa-Ball** [comment]
Je ne sais pas tu utilise hangout.

2018-07-11 16:35 GMT+00:00 ben5blg <notifications@github.com>:

**Comment by ben5blg** [comment]
Non pourquoi ?

**Comment by suchomar** [comment]
There is a problem in Qt 5.11 with nativeEvent parameter *message see: https://bugreports.qt.io/browse/QTBUG-67095
In
`bool Studio::Softer::Windows::Window::nativeEvent(const QByteArray& eventType, void* message, long* result)`
change
`auto msg = static_cast<MSG *>(message);`
to
`auto msg = *static_cast<MSG **>(message);`

or to something like this
```
#if QT_VERSION == QT_VERSION_CHECK(5,11,1)
    auto msg = *static_cast<MSG**>(message);
#else
    auto msg = static_cast<MSG*>(message);
#endif
```

**Comment by ghost** [comment]
Thank you !!!! You saved me so much time

**Comment by ghost** [comment]
it's working
